### PR TITLE
Syntax highlighting in README

### PR DESCRIPTION
**Pull request by mikerodrigues**

### CODE REVIEW

**Comment by ioquatix** [comment]
This is awesome, but is there anyway to do this without making the raw README less readable (i.e. not outdenting all the code?

**Comment by mikerodrigues** [comment]
I'm not sure. I originally left it all indented, only adding the tags for SH. When I previewed it on github it was oddly indented within the box, and required scrolling to see even to 80 characters on some line.

The first commit is like that. Looking at the preview now, it looks fine:

https://github.com/mikerodrigues/process-group/blob/2dfa9db8b6ac1ad30503334eec6070c600476838/README.md

**Comment by mikerodrigues** [comment]
I created a new branch with just the original commit, but it looks different than the preview in the previous link, despite this new branch being from 2dfa9d.

https://github.com/mikerodrigues/process-group/tree/fix-indent

**Comment by ioquatix** [comment]
I'm going to merge this, I think it's a good improvement, thanks for your time and effort.

**Pull request closed without merging**
